<a href="https://colab.research.google.com/github/Mlnvl/python_classp/blob/main/VGProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Step 1: Select a Dataset

I choose the data set Video Game Sales 2024 from kaggle.

https://www.kaggle.com/datasets/asaniczka/video-game-sales-2024/data

#Step 2: Tasks and Requirements

In [30]:
#import dataset from google drive
from google.colab import drive
drive.mount('/content/drive')

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [69]:
#import dataset from google drive
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Pandas_data/Video_Games_Sales_as_at_22_Dec_2016.csv')

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [32]:
df.head()

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
df.columns

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Index(['Name', 'Platform', 'Year_of_Release', 'Genre', 'Publisher', 'NA_Sales',
       'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales', 'Critic_Score',
       'Critic_Count', 'User_Score', 'User_Count', 'Developer', 'Rating'],
      dtype='object')

In [58]:
try:
  import janitor
except:
  print("Module is not preinstalled!Installing now...")
  !pip install pyjanitor --quiet

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [70]:
from janitor import clean_names

df = clean_names(df)
df.columns

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Index(['name', 'platform', 'year_of_release', 'genre', 'publisher', 'na_sales',
       'eu_sales', 'jp_sales', 'other_sales', 'global_sales', 'critic_score',
       'critic_count', 'user_score', 'user_count', 'developer', 'rating'],
      dtype='object')

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16717 non-null  object
 1   platform         16719 non-null  object
 2   year_of_release  16450 non-null  float64
 3   genre            16717 non-null  object
 4   publisher        16665 non-null  object
 5   na_sales         16719 non-null  float64
 6   eu_sales         16719 non-null  float64
 7   jp_sales         16719 non-null  float64
 8   other_sales      16719 non-null  float64
 9   global_sales     16719 non-null  float64
 10  critic_score     8137 non-null   float64
 11  critic_count     8137 non-null   float64
 12  user_score       10015 non-null  object
 13  user_count       7590 non-null   float64
 14  developer        10096 non-null  object
 15  rating           9950 non-null   object
dtypes: float64(9), object(7)
memory usage: 2.0+ MB

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [61]:
df.isnull().sum()

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

name                  2
platform              0
year_of_release     269
genre                 2
publisher            54
na_sales              0
eu_sales              0
jp_sales              0
other_sales           0
global_sales          0
critic_score       8582
critic_count       8582
user_score         6704
user_count         9129
developer          6623
rating             6769
dtype: int64

In [71]:
# Supposons que votre DataFrame s'appelle 'df'
# et que vous souhaitez supprimer les colonnes 'colonne1', 'colonne2' et 'colonne3'.

columns_to_drop = ['critic_score', 'critic_count','user_count','developer','rating']

# Méthode 1 : Utilisation de drop()
df = df.drop(columns=columns_to_drop)

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [49]:
df.isnull().sum()

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

name                  2
platform              0
year_of_release     269
genre                 2
publisher            54
na_sales              0
eu_sales              0
jp_sales              0
other_sales           0
global_sales          0
user_score         6704
dtype: int64

In [72]:
df = df[df["year_of_release"].notnull()]
df = df[df["genre"].notnull()]
df = df[df["publisher"].notnull()]
df['year_of_release'] = pd.to_numeric(df['year_of_release'], errors='coerce').astype('Int64')
df['user_score']=df['user_score'].replace('tbd',0).astype('float64')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16416 entries, 0 to 16718
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16416 non-null  object
 1   platform         16416 non-null  object
 2   year_of_release  16416 non-null  Int64
 3   genre            16416 non-null  object
 4   publisher        16416 non-null  object
 5   na_sales         16416 non-null  float64
 6   eu_sales         16416 non-null  float64
 7   jp_sales         16416 non-null  float64
 8   other_sales      16416 non-null  float64
 9   global_sales     16416 non-null  float64
 10  user_score       9837 non-null   float64
dtypes: Int64(1), float64(6), object(4)
memory usage: 1.5+ MB

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [51]:
df.describe().transpose()

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,count,mean,std,min,25%,50%,75%,max
year_of_release,16416.0,2006.489888,5.881148,1980.0,2003.0,2007.0,2010.0,2020.0
na_sales,16416.0,0.264129,0.819028,0.0,0.0,0.08,0.24,41.36
eu_sales,16416.0,0.146034,0.507134,0.0,0.0,0.02,0.11,28.96
jp_sales,16416.0,0.078623,0.311348,0.0,0.0,0.0,0.04,10.22
other_sales,16416.0,0.04767,0.188156,0.0,0.0,0.01,0.03,10.57
global_sales,16416.0,0.536708,1.559885,0.01,0.06,0.17,0.47,82.53
user_score,9837.0,5.405489,3.318127,0.0,2.4,6.9,8.0,9.7

In [64]:
df.shape

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

(16416, 11)

In [54]:
df = df.dropna(axis=0)

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [56]:
df.describe().transpose()

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,count,mean,std,min,25%,50%,75%,max
year_of_release,9837.0,2007.63007,4.117786,1985.0,2005.0,2008.0,2010.0,2020.0
na_sales,9837.0,0.316552,0.823076,0.0,0.05,0.12,0.3,41.36
eu_sales,9837.0,0.182119,0.585126,0.0,0.01,0.04,0.15,28.96
jp_sales,9837.0,0.046121,0.242058,0.0,0.0,0.0,0.0,6.5
other_sales,9837.0,0.064409,0.229266,0.0,0.01,0.02,0.05,10.57
global_sales,9837.0,0.609453,1.66844,0.01,0.08,0.21,0.56,82.53
user_score,9837.0,5.405489,3.318127,0.0,2.4,6.9,8.0,9.7

In [73]:
df['user_score'] = df['user_score'].fillna(df['user_score'].mean())

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [74]:
df.describe().transpose()

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,count,mean,std,min,25%,50%,75%,max
year_of_release,16416.0,2006.489888,5.881148,1980.0,2003.0,2007.0,2010.0,2020.0
na_sales,16416.0,0.264129,0.819028,0.0,0.0,0.08,0.24,41.36
eu_sales,16416.0,0.146034,0.507134,0.0,0.0,0.02,0.11,28.96
jp_sales,16416.0,0.078623,0.311348,0.0,0.0,0.0,0.04,10.22
other_sales,16416.0,0.04767,0.188156,0.0,0.0,0.01,0.03,10.57
global_sales,16416.0,0.536708,1.559885,0.01,0.06,0.17,0.47,82.53
user_score,16416.0,5.405489,2.568513,0.0,5.405489,5.405489,7.3,9.7